version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=faq_project.settings
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"